---
image: python:3.7.3-alpine

lint_yaml_files:
  script:
    - pip install yamllint
    - find . -type f -name '*.yml' | sed 's|\./||g' | egrep -v '(\.kitchen/|\[warning\]|\.molecule/)' | xargs yamllint -c yamllint.conf -f parsable

#test:
#  script:
    # Spin up a DO droplet to deploy to using Terraform
    #- make terraform
    # Deploy jellyfin to droplet

    # Ensure jellyfin access works

    # Tear down droplet


pages:
  script:
    - pip install mkdocs
    - pip install mkdocs-material
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - master

...
