---
- name: Make wekan directory.
  file:
    path: "/var/homelabos/wekan"
    state: directory

- name: Copy wekan docker-compose.yml file into place.
  template:
    src: docker-compose.wekan.yml.j2
    dest: /var/homelabos/wekan/docker-compose.wekan.yml

- name: Configure wekan systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/wekan.service

- name: Start wekan
  systemd:
    name: wekan
    enabled: "yes"
    daemon-reload: "yes"
    state: started
