---
- name: Make tick directory.
  file:
    path: "/var/homelabos/tick"
    state: directory

- name: Copy tick docker-compose.yml file into place.
  template:
    src: docker-compose.tick.yml.j2
    dest: /var/homelabos/tick/docker-compose.tick.yml


- name: Configure telegraf
  template: src=telegraf.conf.j2 dest=/var/homelabos/tick/telegraf.conf

- name: Configure tick systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/tick.service

- name: Start tick
  systemd:
    name: tick
    enabled: "yes"
    daemon-reload: "yes"
    state: started
