---
- name: Make gitea directory.
  file:
    path: "/var/homelabos/gitea"
    state: directory

- name: Copy gitea docker-compose.yml file into place.
  template:
    src: docker-compose.gitea.yml.j2
    dest: /var/homelabos/gitea/docker-compose.gitea.yml


- name: Configure gitea systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/gitea.service

- name: Start gitea
  systemd:
    name: gitea
    enabled: "yes"
    daemon-reload: "yes"
    state: started
