---
- name: Configure Dasher
  template: src=dasher.config.json dest=/var/homelabos/dasher/config.json

- name: Make dasher directory.
  file:
    path: "/var/homelabos/dasher"
    state: directory

- name: Copy dasher docker-compose.yml file into place.
  template:
    src: docker-compose.dasher.yml.j2
    dest: /var/homelabos/dasher/docker-compose.dasher.yml


- name: Configure dasher systemd service.
  template:
    src: service.j2
    dest: /etc/systemd/system/dasher.service

- name: Start dasher
  systemd:
    name: dasher
    enabled: "yes"
    daemon-reload: "yes"
    state: started
