---
- name: Restart services
  systemd:
    name: "{{ service_item }}"
    state: restarted
  when: "lookup('vars', 'enable_' ~ service_item)"
  loop: "{{ enabled_services|flatten(levels=1) }}"
  loop_control:
    loop_var: service_item
