---
- name: remove enabled services.
  file:
    state: absent
    path: "/var/homelabos/{{ service_item }}"
  when: confirm_remove
  loop: "{{ enabled_services|flatten(levels=1) }}"
  loop_control:
    loop_var: service_item

- name: Ensure disabled services are not running
  systemd:
    name: "{{ service_item }}"
    state: stopped
    enabled: false
  when: "not lookup('vars', 'enable_' ~ service_item) and confirm_remove"
  loop: "{{ enabled_services|flatten(levels=1) }}"
  loop_control:
    loop_var: service_item
  ignore_errors: "yes"

- name: remove enabled services.
  file:
    state: absent
    path: "/etc/systemd/system/{{ service_item }}.service"
  when: confirm_remove
  loop: "{{ enabled_services|flatten(levels=1) }}"
  loop_control:
    loop_var: service_item

- when: confirm_remove
  debug:
    msg: "Package removed successfully! Go to https://{{ domain }}/ to get started."

- debug:
    msg: "Problems? File an issue at https://gitlab.com/NickBusey/HomelabOS/issues"
